# https://github.com/iamawatermelo/wakapi-anyide v0.2.0

[meta]
version = 1

[files]
include = ["*"]  # files to include in tracking
exclude = []  # files to exclude in tracking
exclude_files = [".gitignore"]  # files whose contents will be used to exclude other files from tracking

[project]
name = "RoyalMail"  # your project name